<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>MinimumOSVersion</key>
	<string>9.3</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIStatusBarHidden</key>
	<true/>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>UIFileSharingEnabled</key>
	<true/>
	<key>CFBundleDisplayName</key>
	<string>SmartScope</string>
	<key>CFBundleIdentifier</key>
	<string>com.lab-nation.smartscope</string>
	<key>CFBundleShortVersionString</key>
	<string>VersionPlaceHolder</string>
	<key>CFBundleName</key>
	<string>SmartScope</string>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/AppIcon.appiconset</string>
	<key>XSLaunchImageAssets</key>
	<string>Assets.xcassets/LaunchImage.launchimage</string>
	<key>CFBundleVersion</key>
	<string>VersionCodePlaceHolder</string>
</dict>
</plist>
